language: cpp

matrix:
  include:

    # gcc-7
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # clang 7.0
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-7-dev
            - clang-tidy-7
      env:
        - MATRIX_EVAL=""

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir cmake-build-test
  - cd cmake-build-test
  - cmake ..

script:
  - make
  - test/unittest/EasyExceptionUnitTest
  - test/integrationtest/EasyExceptionIntegrationTest
  - ./CustomException
  - ./JsonException
  - ./SimpleException
  - ./SimpleStacktrace
  - ./DefaultLogging
  - ./LoggerInheritance
  - ./SignalHandler
  - ./DefaultConfiguration || true
  - ./UncaughtException || true

  - mkdir $TRAVIS_BUILD_DIR/cmake-build-tidy
  - cd $TRAVIS_BUILD_DIR/cmake-build-tidy
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - $TRAVIS_BUILD_DIR/tools/run-clang-tidy.py $TRAVIS_BUILD_DIR/cmake-build-tidy